### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by DavidFW1960** [azzy9/plugin.video.rumble#1]
Decided to create the issue and move the discussion here - hope that's ok.
The subscription function is working
But it's sorting everything to show videos from my subscribed channels.
Could it be shown so it just displays my subscribed channels - not the individual videos. Then I can just select a channel and switch to it to see the videos in that channel. - Same as if I use a web browser, the subscriptions shows the subscribed channels and you can then select the channel to drill down...

**Comment by azzy9** [comment]
Hi, In v1.2.1 the "following" section was added which shows followed channels. is this feature request different from this?

**Comment by DavidFW1960** [comment]
I'm an idiot. I was expecting to see it under subscriptions but it is under following. Perfect and many thanks.
