### ISSUE TITLE
But: Following Category Not Working. 

### ISSUE THREAD

**Issue by neo-neo1** [azzy9/plugin.video.rumble#10]
The "Following" category stopped working. It's simply blank when opened.

Using Rumble 1.4.2

---------------------

But = Bug**

**Comment by azzy9** [comment]
Could you try v1.4.3 to see if the issue persists

**Comment by neo-neo1** [comment]
> Could you try v1.4.3 to see if the issue persists

Perfect, 1.4.3 fixed it. Thanks for the quick work

**Comment by neo-neo1** [comment]
> Could you try v1.4.3 to see if the issue persists

I spoke too soon, sorry.

While channels names are listed within "Following" opening up any channel gives blank results.

**Comment by azzy9** [comment]
Thanks again, should be fixed in v1.4.4
