### ISSUE TITLE
Bug: Subscription Feed Not Working

### ISSUE THREAD

**Issue by neo-neo1** [azzy9/plugin.video.rumble#11]
Subscription Feed stopped working, just blank. 

And Following feed also has problems, shows channels I'm not following.

Rumble API change or something? 

Thanks for your continued maintenance and support I use this addon almost daily.

**Comment by azzy9** [comment]
Sounds like the session is failing, The channels showing that you have not followed is because if you are not logged in, the site gives recommendations.

To reset the session
go to settings -> login -> reset session

**Comment by neo-neo1** [comment]
> Sounds like the session is failing, The channels showing that you have not followed is because if you are not logged in, the site gives recommendations.
> 
> To reset the session go to settings -> login -> reset session

Thank you. Got it.

 BTW have you experienced constant live stream drops? I just enabled HTTP from debug to see if it'll fix it.
