### ISSUE TITLE
Subscriptions Pages Issue

### ISSUE THREAD

**Issue by neo-neo1** [azzy9/plugin.video.rumble#13]
When viewing "Subscriptions" the "Page 2" (and "Page 3" and etc...) button doesn't work. It just refreshes and shows the same list as Page 1.

Using Rumble 1.4.5 Addon 

Many thanks in advance

**Comment by azzy9** [comment]
Hi, Thanks for reporting.
I can replicate the issue and will push a fix when I get the time

**Comment by azzy9** [comment]
Should be fixed in v1.4.6

**Comment by neo-neo1** [comment]
> Should be fixed in v1.4.6

Perfect, thanks! But, just noticed identical issue in "Following". Sorry for all the reports. 

Thanks for your quick and continued maintenance of this vital Addon

**Comment by azzy9** [comment]
I actually don't know how the plugin handles following many channels since I only subscribed to a few. I don't think this one is going to be as easy as it scrapes the followed channels from the left hand side menu which doesn't have pagination.

**Comment by neo-neo1** [comment]
> I actually don't know how the plugin handles following many channels since I only subscribed to a few. I don't think this one is going to be as easy as it scrapes the followed channels from the left hand side menu which doesn't have pagination.

No worries, not a priority. Addon is still usable as is with all current major bugs fixed.

**Comment by neo-neo1** [comment]
> This should now be fixed in v1.4.7. The following was not showing all subscribed channels as the regex was not catching them all. I also removed the pagination as it isn't needed for following as it shows them all

Perfect! Thanks again
