### ISSUE TITLE
stopped working again

### ISSUE THREAD

**Issue by Pi-MONSTER** [azzy9/plugin.video.rumble#14]
I'm finding it is hanging machines on all but "favourites" and "leader board"
even search does not work now

**Comment by azzy9** [comment]
Hi @Pi-MONSTER,
Thanks for reporting this issue.
Please could you try v1.4.9 & see if it fixes your issue :)

**Comment by Pi-MONSTER** [comment]
Channels are back again :-)

BUT as stated SEARCH doesn't save channels on finding channels it states on the second line next to the subscription size "No videos or channels added to favourites".

I'm also finding I cant delete saved channels, selecting to save "favourite" does nothing no error, but selecting "rumble favourites" indicates error

In kodi log:

line 794, in video.rumble/main.py
	Traceback (most recent call last):
Error contents: invalid literal for int() with base 10:'False'
ErrorType: <class ValueError>


UPDATE:
Tried a manual hack of favourites file, changing 'channel', 'False','2' to 'True,'1'
But no cant fool it.

**Comment by azzy9** [comment]
That error should be fixed this commit:
https://github.com/azzy9/plugin.video.rumble/commit/5cd94c2ebc059fd59f00876f2116be8716178751

I will need to look into why it is always showing "No videos or channels added to favourites" before I release the fixes as a release.

**Comment by azzy9** [comment]
Turned out to be the wrong string id.
Now released v1.4.10 with the fixes

**Comment by Pi-MONSTER** [comment]
Super fast bug fix ! 
All working good now :-)

**Comment by azzy9** [comment]
Awesome to hear
