### ISSUE TITLE
Display viewed video mark

### ISSUE THREAD

**Issue by karlo2105** [azzy9/plugin.video.rumble#17]
I would like to ask you if you could add watched video mark? 
Could you also make a repo in order to get automatic updates? If not, never mind.
Thanks.

**Comment by azzy9** [comment]
Hi, I cannot replicate the issue, which version of Kodi are you using?

Unfortunately I have no plans to create a repository

**Comment by karlo2105** [comment]
I use the latest stable Kodi 20.2. On other platforms such us Youtube, Odysee, Dailymotion, fully watched video is marked. There is time icon within partly watched videos. On Rumble, there isn't any mark viewed videos.

**Comment by azzy9** [comment]
I use Kodi 20.2, I cannot replicate this issue, but I shall see what I can do.

**Comment by azzy9** [comment]
The reason I couldn't replicate it is that I used confluence theme, I changed the theme to estuary and then had the same issue. The plugin requires inform Kodi of the content type with "xbmcplugin.setContent(PLUGIN_ID, 'videos')".
I shall push an update when I have time

**Comment by karlo2105** [comment]
@azzy9 
Addendum
Partially watched video is symbolised by circle. Thanks for support.

**Comment by azzy9** [comment]
Should be fixed in v1.4.15
