### ISSUE TITLE
Following or Favorites Menu doesn't work

### ISSUE THREAD

**Issue by neo-neo1** [azzy9/plugin.video.rumble#18]
Using latest Rumble 1.4.16

When browsing "Following" or "Favorites"  menus, going into any channel brings up 0 results.

Thanks in advance form your upkeep.

P.S. Please consider having a Kodi repository. It'll help for more people to discover this great app (and devs too).

**Comment by azzy9** [comment]
I can confirm and replicate this issue.
Only channels (not user) pages have had its layout changed.
I shall fix this when I have time.

**Comment by Pi-MONSTER** [comment]
ALSO search fails to find channels.

**Comment by azzy9** [comment]
@neo-neo1 & @Pi-MONSTER Thanks for reporting, should be fixed in v1.4.17
