### ISSUE TITLE
Video freeze or stops

### ISSUE THREAD

**Issue by Isayso** [azzy9/plugin.video.rumble#2]
Thank you for your fork.
I have problems that the video freeze, audio runs further on Libreelec.
If I jump some seconds back, the video runs again.
Sometimes the video stops completely.

Thanks!

**Comment by azzy9** [comment]
Unfortunately there is not much I can do here.
This plugin simply gets the video link and passes it to Kodi, so it has no bearing on how Kodi treats the video.
Some methods to try to stop the issues:
https://www.firesticktricks.com/fix-kodi-buffering.html

**Comment by DavidFW1960** [comment]
I haven't had any issues at all with streams.

**Comment by Isayso** [comment]
Thanks, 
I see this only with Rumble videos and there is no "buffering" message, so it does not look like a buffer issue, audio is still running only the video frame freezes. Libreelec has several issues for a long time with audio/video sync or stutter, could be a player problem from Libreelec. Looks like it appears after 4+ min video running.
Will try to generate an error message.

**Comment by dbms-error** [comment]
Had the same issue around the same time as Isayso. Worked fine the next day and since.

**Comment by Isayso** [comment]
Had the same effect now at an Odysee video, that's new. That seems to be a Kodi/Libreelec problem.

**Comment by azzy9** [comment]
Thank you all for your input, not much I can do for this so will mark as wont fix

**Comment by Isayso** [comment]
I got the usual answer from the kodi team regarding Rumble or Odysee, they declare this as piracy related. It is not the first time I get such answers regarding playing Rumble.  In general, I'm getting sick of Kodi, I watch a lot music videos, there are so many audio bugs not fixed for years. I would like to have an alternative on RPIs.

**Comment by azzy9** [comment]
there is this thread on reddit: https://www.reddit.com/r/Addons4Kodi/comments/10u9rug/kodi_nexus_keeps_crashing_streams/
Some people say V21 beta seems stable. But if you go that route I would back-up your current setup first

**Comment by Isayso** [comment]
Thanks! I will use a separate SD card, I tried LE 11 (wich is Nexus) some weeks ago and it was very unstable on the RPI3x.
I try OSMC (Matrix) today and the first result on Rumble looks not bad. There is a frame drop, jump and an audio crack, but not a broken stream so far. (But I have problems with widewine on OSMC) Will keep you informed.

**Comment by DavidFW1960** [comment]
> I try OSMC

I use OSMC on a Vero 4 and I don't get any skips. It works very well. No problems with Widevine either

**Comment by Isayso** [comment]
Spend the whole evening on OSMC set-up and was running in so many quirks and bugs, not sure if I should invest more time. 
Looks like LE and OSMC dropped support of RPI2/3. Even simple tasks like connect to nfs in filemanager is not what you think or SMB or do a backup of settings. I tried to install widewine 3 times and got a sad face on screen afterwards. 60fps not running is equal to LE. Buying new hardware is not an option, the RPI4 is a dead horse (everywhere sold-out) and I will not spend 139€ for a Vero.

**Comment by Isayso** [comment]
Update: Looks like it is working in Kodi 20 (LE11 beta) :-)

**Comment by azzy9** [comment]
@Isayso Awesome to hear 👍
