### ISSUE TITLE
Channel Name in Subscriptions?

### ISSUE THREAD

**Issue by neo-neo1** [azzy9/plugin.video.rumble#21]
When viewing **Subscriptions** menu on 1.4.18, it now only displays title of the video. Can the channel name be included similar to how the YouTube Addon is?

Thanks in advance

**Comment by azzy9** [comment]
I know this is an issue, which is why I called it a quick fix in the v1.4.18 update.
I will eventually get around to fix it, Rumble keep adding more stuff into the HTML so it becomes more complex to write the REGEX

**Comment by azzy9** [comment]
Should be fixed in v1.5.1
