### ISSUE TITLE
Bugfix Request: No German Umlauts are shown

### ISSUE THREAD

**Issue by SingleMalt2104** [azzy9/plugin.video.rumble#24]
When there should be German Umlauts shown, i.e. in the headline description text, there is none to see. So the word is incomplete.
For example, if there should be the word "Änderung", only "nderung" is actually shown. At that point you have to guess that there should be an Umlaut.

**Comment by azzy9** [comment]
Do you have any channels I could use to test?

**Comment by SingleMalt2104** [comment]
https://rumble.com/v4684yz-hau-ab-hau-ab-zdemir-bei-brgerdialog-gnadenlos-ausgepfiffen.html
The headline should read: "Hau ab, hau ab!" – Özdemir bei Bürgerdialog gnadenlos ausgepfiffen
But the "Ö" and the "ü" is missing.

**Comment by azzy9** [comment]
This issue was caused by code to make the plugin compatible with python 2 & 3, I have limited it to Python 2 so as long as you are using Kodi 19+ This issue is fixed in v1.5.3.

**Comment by SingleMalt2104** [comment]
@azzy9

Thanks azzy9, with your new v1.5.3 German Umlauts (ä,ö,ü) are now being displayed fine. To verify this I used my above mentioned examples, and now they are displayed with Umlauts, as they should.
