### ISSUE TITLE
Following category empty on some channels

### ISSUE THREAD

**Issue by karlo2105** [azzy9/plugin.video.rumble#27]
I would like to point out that some channels display empty list of videos in the latest plugin rumble 1.5.3.
You can check out by yourself : 

https://rumble.com/user/ANIAK44
https://rumble.com/user/BadVolf
https://rumble.com/user/SLOBODNIpodcast
https://rumble.com/user/Wakeup000

Thanks for maintenance

**Comment by azzy9** [comment]
le sigh, HTML has been changed again, a few things are broken such as search and will need to be fixed

**Comment by azzy9** [comment]
Should be fixed in v1.5.4
