### ISSUE TITLE
Following not working properly?

### ISSUE THREAD

**Issue by DavidFW1960** [azzy9/plugin.video.rumble#3]
Seems to give random channels I have never followed and all out of order.

**Comment by DavidFW1960** [comment]
Ah I just reset it and it seems to be working correctly again....

**Comment by azzy9** [comment]
Sorry, been away for a while and just returned so I have only just seen this.
The following page gets its channels from the left side bar, which if not logged in is the popular channels.
When you reset the session, it done a new login and fixed the issue.

**Comment by DavidFW1960** [comment]
It's weird because I had to reset the session again today and it didn't refresh. When I then went to page 2 it was showing my followings...

**Comment by azzy9** [comment]
Hi @DavidFW1960, is this still an issue or is it safe to close this?

**Comment by DavidFW1960** [comment]
seems to be fixed with the cookie changes you made. Thanks!
