### ISSUE TITLE
Bug: Following Broken

### ISSUE THREAD

**Issue by neo-neo1** [azzy9/plugin.video.rumble#33]
Opening any channel under "Following" shows no results. Using Rumble 1.6.1 

Thanks for your work as usual.

**Comment by azzy9** [comment]
Hi @neo-neo1, Unfortunately, I cannot replicate the issue.
Could you try to reset your session in the settings?
Is this happening to any channel in your following in specific?

**Comment by neo-neo1** [comment]
> Hi @neo-neo1, Unfortunately, I cannot replicate the issue. Could you try to reset your session in the settings? Is this happening to any channel in your following in specific?

Strange, resting session did fix it. Issue only affected following not populating — identical as an earlier issue. Sorry for the false alarm.
