### ISSUE TITLE
Question: Compatible with Kodi 21?

### ISSUE THREAD

**Issue by neo-neo1** [azzy9/plugin.video.rumble#34]
Sorry if I'm misusing GitHub, but I found no other place to ask. I didn't see Kodi compatibility in the Readme. 

I'm currently using Kodi 20 – and use this Addon frequently. Is this Addon compatible with Kodi 21? 
I'm looking to update but want to verify compatibility before doing so.

As always, much appreciated.

**Comment by azzy9** [comment]
Hi @neo-neo1,
The rumble plugin does work on kodi 21,

The only one of my plugins that have an issue is the LBRY+ plugin which kodi 21 has an issue with 1/2 the thumbnails.
This is on Kodi's side so nothing I can do about it.
