### ISSUE TITLE
Missing some of subscribed channels under following menu

### ISSUE THREAD

**Issue by jiffypop2** [azzy9/plugin.video.rumble#35]
Not all my subscribed channels are showing up under the following menu. Only 20 of my channels that I follow show up on the list. I have tried this on Kodi 20 and Kodi 21

**Comment by karlo2105** [comment]
I confirm the stance. Out of 41 subscribed channels, 20 are displayed only and I can't access the rest.

**Comment by azzy9** [comment]
The plugin gets the following from the left hand menu from the site, I was going to write that the following page does not have images so could not really use that, but they must have recently updated that page (https://rumble.com/followed-channels) and should be able to use it instead to get all the followed channels.
