### ISSUE TITLE
Bug: Videos not appearing for channels which have a live stream

### ISSUE THREAD

**Issue by neo-neo1** [azzy9/plugin.video.rumble#37]
For Rumble channels which have a 24/7 live stream, they show 0 videos under the "Following" category. Their respective videos do show up under the "Subscriptions" category, just not under "Following"

**How to replicate bug:**

1). Follow any channel which has a 24/7 live stream. 

Examples: 
[TNT Radio](https://rumble.com/c/tntradiolive)
[Infowars](https://rumble.com/c/Infowars)
[RT](https://rumble.com/c/Infowars)
Any many others.

2). Go to "Following" category, open the respective channel, and it'll show blank results. No videos are listed for the channel.

As usual, thanks for your continued work on this project azzy9

**Comment by azzy9** [comment]
Thanks, Should be fixed in v1.7.1
