### ISSUE TITLE
Bug: Following Category Missing Names

### ISSUE THREAD

**Issue by neo-neo1** [azzy9/plugin.video.rumble#38]
Just as the title says, navigate to the "Following" category and channel names are missing.

Using Rumble 1.7.1

**Comment by azzy9** [comment]
Fixed here: https://github.com/azzy9/plugin.video.rumble/commit/ff59f1e32d39b732c3fbdd4744b4a91762bc879c
Just need to push out a release

**Comment by azzy9** [comment]
Should be fixed in v1.7.2
