### ISSUE TITLE
Weird font/layout issues for listings.

### ISSUE THREAD

**Issue by develroo** [azzy9/plugin.video.rumble#39]
* Plugin Version: 1.7.2
* Kodi Version: OSMC 20.05
* Operating System: Debian aarch64

When browsing lists, of favourites, live, subscriptions or leader board the follow appears and makes it very hard to delimit one element from another. It appears the fonts are too big.

![screenshot00000-obfuscated](https://github.com/user-attachments/assets/85613625-da88-4b77-aec5-b93981e18ab3)

I don't see any font settings in the plugin, so how to fix this? 

Thanks.

**Comment by develroo** [comment]
Hmmm, Well other plugins don't look like that, like the youtube one for example.

Any way to figure out what theme elements are being used ?

**Comment by develroo** [comment]
> One thing you could try is changing the view mode.

In what sense? I mean, I mean I tried Kodi default theme and see if the problem is replicated, but seems to scaled better  with different sized fonts

![Screenshot from 2024-07-17 10-56-24](https://github.com/user-attachments/assets/4c88a550-7f1d-4de5-9b86-f2ceab93428c)

It could be because there is no implied theming things get messed up, though I do notice a `resources/skins/default/720p` which seems curious.

**Comment by azzy9** [comment]
the file https://github.com/azzy9/plugin.video.rumble/blob/master/resources/skins/default/720p/addon-rumble-comments.xml is for displaying comments.
It has to create an overlay which is not usual Kodi behaviour.

The only thing I could really suggest to try and fix your issue is to create an option in settings to put the titles on one line.

**Comment by develroo** [comment]
Hmmm ok.. I will investigate. 

Otherwise, the addon works well. 

Thanks

**Comment by azzy9** [comment]
I have added an option in v1.7.3 to view titles on one line

**Comment by develroo** [comment]
> I have added an option in v1.7.3 to view titles on one line

Yup, can confirm that fixes it for OSMC. 

![screenshot00003](https://github.com/user-attachments/assets/35eb0808-701a-4d50-9bd8-729e6f4fe8c9)


Cheers
