### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by neo-neo1** [azzy9/plugin.video.rumble#4]
Not an issue. 

Just switched from the original OneHd version and I'm grateful. Thank you for your upkeep! I had mostly abandoned watching Rumble solely because the original addon was so unusable. Just being able to login and navigate to followers is pivotal. Thank you

P.S. Does a Kodi repo exist?

**Comment by azzy9** [comment]
Hi, thank you.
I am quite proud with the fact I got the login to work via converting the custom MD5 method from JS to python. so awesome to hear that it is appreciated by people.
Unfortunately I do not have a repo.

**Comment by neo-neo1** [comment]
> Hi, thank you. I am quite proud with the fact I got the login to work via converting the custom MD5 method from JS to python. so awesome to hear that it is appreciated by people. Unfortunately I do not have a repo.

Earlier today I attempted to use Runble Addon and subscriptions category wasn't. Needless to say, thank you again for staying on top of things with constant updates.

No repo still, correct?
