### ISSUE TITLE
PSA: Issue with http2

### ISSUE THREAD

**Issue by azzy9** [azzy9/plugin.video.rumble#5]
For me an issue with http2 has cropped up.
After 6 -16 secs the video will freeze.

I have temporarily fixed it by creating an option in the settings to enforce HTTP instead of HTTPS.

So if you have any issues with videos crashing you can try to enable this.

**Comment by DavidFW1960** [comment]
Haven't seen this issue myself but I'll keep it in mind and install the new version anyway. Thanks for being so proactive.
