### ISSUE TITLE
Feature Request: Queue 

### ISSUE THREAD

**Issue by neo-neo1** [azzy9/plugin.video.rumble#6]
Thanks again for fixing this crucial Kodi addon.
One feature I dearly miss and can't do without is the "Queue" feature from Context Menu. I would greatly appreciate if you could add it.

Similarly to how the YouTube & Twitch Kodi Add-Ons implement Queue from the Context Menu. Having the ability to Queue several videos back-to-back immensely would improves the usability of this Rumble addon.

Again, thanks for all you've done.

**Comment by azzy9** [comment]
HI @neo-neo1, please can you try v1.3.2

**Comment by neo-neo1** [comment]
> HI @neo-neo1, please can you try v1.3.2

Perfect! Thank you for the quick work
