### ISSUE TITLE
Issue adding to favourites

### ISSUE THREAD

**Issue by DavidFW1960** [azzy9/plugin.video.rumble#7]
Hi, this is pretty trivial but with the ONEHD old version, the context menu let you add a channel etc to the Rumble Favourites or the Kodi Favourites menu. Right now that functionality still works BUT when you go to add, it just has 2 lines saying favourites rather than specifying which Favourites is which.

**Comment by azzy9** [comment]
Hi @DavidFW1960, do you mean that the text "Add to favourites" should be changed to something like "Add to plugin favourites" to avoid confusion?

**Comment by DavidFW1960** [comment]
Yes. I think it used to say add to rumble favourites.

**Comment by azzy9** [comment]
I have changed it in the language file via commit https://github.com/azzy9/plugin.video.rumble/commit/63b2222e59855ef2cd50c51c57f7e13f2cd9eb09
when I have got around to test it, I'll release it

**Comment by DavidFW1960** [comment]
I made those changes to the language file and it all seems good here

**Comment by azzy9** [comment]
Thank you @DavidFW1960  for testing

**Comment by DavidFW1960** [comment]
Thank you for being so responsive

**Comment by azzy9** [comment]
Thank you for reporting this issue. This change is now live in v1.3.3, so I will now close this.
